#define MESH_PREFIX_secr    "LiansNetwork"
#define MESH_PASSWORD_secr  "LiansNetwork"
#define token_secr          "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiI4YTMyYWI2ZDMzNGE0MjIzODM5MzIzYzQ4MTE5YzE2OCIsImlhdCI6MTY0OTE2Mjc1NiwiZXhwIjoxOTY0NTIyNzU2fQ.AXA7uUs4cRBxNI0JDZGX1U9fqrxuLeWr_XiN5_jRndk"
#define ssidScan_secr       "home-assistant-AP"
#define passScan_secr       "networkubdx"
